name: Build WebGL Version
on: [ push ]
jobs:
  build-game:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout ðŸ“¥
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        lfs: true

    - name: Cache â™»ï¸
      uses: actions/cache@v2
      with:
        path: Library
        key: Library-WebGL
        restore-keys: |
          Library-WebGL
          Library-

    - name: Build WebGL Version ðŸ”¨
      uses: game-ci/unity-builder@v2
      env:
        UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
      with:
        targetPlatform: WebGL

    - name: Upload Artifact ðŸ“¦
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path: build

    - name: Set env
      run: echo "RELEASE_VERSION=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_ENV

    - name: Publish to itch.io ðŸš€
      uses: josephbmanley/butler-publish-itchio-action@master
      env:
        BUTLER_CREDENTIALS: ${{ secrets.BUTLER_API_KEY }}
        CHANNEL: web
        ITCH_GAME: lowrezjam-2021
        ITCH_USER: skosnowich
        PACKAGE: build/WebGL/WebGL
        VERSION: ${{ env.RELEASE_VERSION }}
